import turtle
bicho = turtle.Turtle()
sc = turtle.Screen ()
bicho.shape("turtle")
sc.bgcolor ("lightgreen")
bicho.color("blue")
bicho.pensize(3)
for _ in range (12):
    bicho.pu()
    bicho.fd(100)
    bicho.pd()
    bicho.fd(15)
    bicho.pu()
    bicho.fd(20)
    bicho.stamp()
    bicho.bk(135)
    bicho.lt(30)
sc.exitonclick ()
turtle.bye ()